# syntax=docker/dockerfile:1
FROM node:22.21.1-trixie-slim AS node

FROM --platform=${BUILDPLATFORM} golang:1.25.1-trixie AS builder

ENV GOTOOLCHAIN=local
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

COPY install-deps.sh /install-deps.sh
RUN /install-deps.sh

# Create build directory
RUN mkdir -p /build/

# Copy go.mod and go.sum
COPY go.mod go.sum /build/

WORKDIR /build

RUN go mod download && go mod verify

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
